services:
  traccar:
    image: traccar/traccar:latest
    restart: unless-stopped
    depends_on:
      - database
    environment:
      CONFIG_USE_ENVIRONMENT_VARIABLES: "true"
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_URL: jdbc:postgresql://database:5432/traccar
      DATABASE_USER: traccar
      DATABASE_PASSWORD: traccar
    healthcheck:
      test:
        ["CMD", "wget", "-q", "--spider", "http://localhost:8082/api/health"]
      interval: 2m
      timeout: 5s
      start_period: 1h
      retries: 3
    ports:
      - "8082:8082"
      - "5000-5500:5000-5500"
    volumes:
      - /opt/traccar/logs:/opt/traccar/logs

  database:
    image: timescale/timescaledb:latest-pg16
    restart: unless-stopped
    environment:
      POSTGRES_DB: traccar
      POSTGRES_USER: traccar
      POSTGRES_PASSWORD: traccar
      TIMESCALEDB_TELEMETRY: "off"
    volumes:
      - /opt/traccar/data:/var/lib/postgresql/data

  autoheal:
    image: willfarrell/autoheal:latest
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
      AUTOHEAL_INTERVAL: 60
      AUTOHEAL_START_PERIOD: 3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  lkt-lns:
    image: lkt-lns:latest
    depends_on:
      - mosquitto
    restart: unless-stopped
    ports:
      - "1700:1700/udp"
      - "1730:1730/udp"

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./configurations/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
